# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-12 18:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_websitesettings_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='websitesettings',
            name='about',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
